### ISSUE TITLE
演示代码还真没有放到 app中

### ISSUE THREAD

**Issue by SomnusWu** [Alex-Cin/Dialog#1]
> 博客地址  http://www.jianshu.com/p/d893ba8608ae
> 
> 源码  https://github.com/Alex-Cin/Dialog
> 
> demo   https://github.com/Alex-Cin/DialogApp

**Comment by Alex-Cin** [comment]
> 博客地址  http://www.jianshu.com/p/d893ba8608ae



> 源码  https://github.com/Alex-Cin/Dialog


> demo   https://github.com/Alex-Cin/DialogApp
