### ISSUE TITLE
error

### ISSUE THREAD

**Issue by angcyo** [Alex-Cin/Dialog#2]
这源码, 是不是还有很多文件没有提交呢?

**Comment by Alex-Cin** [comment]
有 哪些  文件 没提交？能贴一下 吗？我 再提交一下

**Comment by angcyo** [comment]
@drawable/alex_ic_no_data
@drawable/alex_ic_fail
@drawable/alex_ic_no_net

**Comment by Alex-Cin** [comment]
没有  这些 文件 应该 也是 可以运行的吧，这些图片 是 属于我的 另一个 demo的，但是 没法提交到github
了，总是超时，回头我再试试

**Comment by angcyo** [comment]
build  都失败了, 怎么能运行呢?

**Comment by Alex-Cin** [comment]
https://github.com/Alex-Cin/DialogApp
这个 是 运行 的 demo

**Comment by Alex-Cin** [comment]
我当时 只是放上去，没想过 有人会看。。。。回头在整理整理。。

**Comment by angcyo** [comment]
呵呵.
